// Code generated by mockery v2.25.1. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"

	s3 "github.com/aws/aws-sdk-go/service/s3"

	s3manager "github.com/aws/aws-sdk-go/service/s3/s3manager"
)

// S3Downloader is an autogenerated mock type for the S3Downloader type
type S3Downloader struct {
	mock.Mock
}

type S3Downloader_Expecter struct {
	mock *mock.Mock
}

func (_m *S3Downloader) EXPECT() *S3Downloader_Expecter {
	return &S3Downloader_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields: w, input, options
func (_m *S3Downloader) Download(w io.WriterAt, input *s3.GetObjectInput, options ...func(*s3manager.Downloader)) (int64, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, w, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(io.WriterAt, *s3.GetObjectInput, ...func(*s3manager.Downloader)) (int64, error)); ok {
		return rf(w, input, options...)
	}
	if rf, ok := ret.Get(0).(func(io.WriterAt, *s3.GetObjectInput, ...func(*s3manager.Downloader)) int64); ok {
		r0 = rf(w, input, options...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(io.WriterAt, *s3.GetObjectInput, ...func(*s3manager.Downloader)) error); ok {
		r1 = rf(w, input, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// S3Downloader_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type S3Downloader_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - w io.WriterAt
//   - input *s3.GetObjectInput
//   - options ...func(*s3manager.Downloader)
func (_e *S3Downloader_Expecter) Download(w interface{}, input interface{}, options ...interface{}) *S3Downloader_Download_Call {
	return &S3Downloader_Download_Call{Call: _e.mock.On("Download",
		append([]interface{}{w, input}, options...)...)}
}

func (_c *S3Downloader_Download_Call) Run(run func(w io.WriterAt, input *s3.GetObjectInput, options ...func(*s3manager.Downloader))) *S3Downloader_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*s3manager.Downloader), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*s3manager.Downloader))
			}
		}
		run(args[0].(io.WriterAt), args[1].(*s3.GetObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *S3Downloader_Download_Call) Return(n int64, err error) *S3Downloader_Download_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *S3Downloader_Download_Call) RunAndReturn(run func(io.WriterAt, *s3.GetObjectInput, ...func(*s3manager.Downloader)) (int64, error)) *S3Downloader_Download_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewS3Downloader interface {
	mock.TestingT
	Cleanup(func())
}

// NewS3Downloader creates a new instance of S3Downloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewS3Downloader(t mockConstructorTestingTNewS3Downloader) *S3Downloader {
	mock := &S3Downloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
